[build]
  command = "yarn build"
  publish = "dist"
  node_version = "20"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 