/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/DPM-legs.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="DPM1" position={[4.65, -5.96, -15.47]} rotation={[0, 0.02, 0]} scale={3.05}>
          <primitive object={nodes.Hips} />
          <skinnedMesh name="Wolf3D_Body001" geometry={nodes.Wolf3D_Body001.geometry} material={materials['Wolf3D_Body.001']} skeleton={nodes.Wolf3D_Body001.skeleton} />
          <skinnedMesh name="Wolf3D_Hair001" geometry={nodes.Wolf3D_Hair001.geometry} material={materials['Wolf3D_Hair.001']} skeleton={nodes.Wolf3D_Hair001.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Bottom001" geometry={nodes.Wolf3D_Outfit_Bottom001.geometry} material={materials['Wolf3D_Outfit_Bottom.001']} skeleton={nodes.Wolf3D_Outfit_Bottom001.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Top001" geometry={nodes.Wolf3D_Outfit_Top001.geometry} material={materials['Material.023']} skeleton={nodes.Wolf3D_Outfit_Top001.skeleton} />
          <skinnedMesh name="EyeLeft001" geometry={nodes.EyeLeft001.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft001.skeleton} morphTargetDictionary={nodes.EyeLeft001.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft001.morphTargetInfluences} />
          <skinnedMesh name="EyeRight001" geometry={nodes.EyeRight001.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight001.skeleton} morphTargetDictionary={nodes.EyeRight001.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight001.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Beard001" geometry={nodes.Wolf3D_Beard001.geometry} material={materials['Wolf3D_Beard.001']} skeleton={nodes.Wolf3D_Beard001.skeleton} morphTargetDictionary={nodes.Wolf3D_Beard001.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Beard001.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Head001" geometry={nodes.Wolf3D_Head001.geometry} material={materials['Wolf3D_Skin.001']} skeleton={nodes.Wolf3D_Head001.skeleton} morphTargetDictionary={nodes.Wolf3D_Head001.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head001.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Teeth001" geometry={nodes.Wolf3D_Teeth001.geometry} material={materials['Wolf3D_Teeth.003']} skeleton={nodes.Wolf3D_Teeth001.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth001.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth001.morphTargetInfluences} />
        </group>
        <group name="Object_4" rotation={[-Math.PI, 0, 0]} scale={27.13}>
          <group name="Object_5001" />
        </group>
        <group name="Object_7001" rotation={[-Math.PI, 0, 0]} scale={27.13}>
          <group name="Object_8" />
        </group>
        <group name="Object_10" rotation={[-Math.PI, 0, 0]} scale={27.13}>
          <group name="Object_11" />
        </group>
        <group name="Secret_Garden_729_Space_portal" position={[0.81, -0.1, -22.05]} rotation={[0, 1.57, 0]}>
          <group name="Untitled_19_Embers_geo">
            <mesh name="Untitled_19_Embers_geo_Embers_0" geometry={nodes.Untitled_19_Embers_geo_Embers_0.geometry} material={materials.Embers} position={[1.71, -0.2, 5.36]} />
          </group>
          <group name="Untitled_19_Fire_geo">
            <mesh name="Untitled_19_Fire_geo_Fire_0" geometry={nodes.Untitled_19_Fire_geo_Fire_0.geometry} material={materials.Fire} position={[1.71, -0.2, 5.36]} />
          </group>
          <group name="Untitled_19_Light_geo">
            <mesh name="Untitled_19_Light_geo_Light_0" geometry={nodes.Untitled_19_Light_geo_Light_0.geometry} material={materials.Light} position={[1.71, -0.2, 5.36]} />
          </group>
          <group name="Untitled_19_Stars_geo">
            <mesh name="Untitled_19_Stars_geo_Stars_0" geometry={nodes.Untitled_19_Stars_geo_Stars_0.geometry} material={materials.Stars} position={[1.71, -0.2, 5.36]} />
          </group>
        </group>
        <PerspectiveCamera name="Camera" makeDefault={false} far={99.6} near={0.1} fov={26.3} position={[0.1, 1.86, 0.13]} rotation={[-0.13, 0.03, 0.02]} />
        <mesh name="Frame_1" geometry={nodes.Frame_1.geometry} material={materials['initialShadingGroup.001']} position={[3.68, 1.23, -15.16]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={1.21} />
        <mesh name="Frame_1001" geometry={nodes.Frame_1001.geometry} material={materials['initialShadingGroup.001']} position={[3.74, 1.25, -19.3]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={1.21} />
        <mesh name="Frame_1002" geometry={nodes.Frame_1002.geometry} material={materials['initialShadingGroup.001']} position={[-4.52, 0.81, -19.3]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={1.21} />
        <mesh name="Frame_1003" geometry={nodes.Frame_1003.geometry} material={materials['initialShadingGroup.001']} position={[-4.77, 0.81, -23.7]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={1.21} />
        <mesh name="Earth" geometry={nodes.Earth.geometry} material={materials['Scene_-_Root']} position={[-4.27, 0.68, -15.27]} scale={0.65} />
        <mesh name="Frame_1004" geometry={nodes.Frame_1004.geometry} material={materials['initialShadingGroup.001']} position={[-4.27, 0.75, -15.27]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={1.21} />
        <mesh name="Frame_1005" geometry={nodes.Frame_1005.geometry} material={materials['initialShadingGroup.001']} position={[4.38, 0.95, -23.59]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={1.21} />
        <mesh name="Human_Brain" geometry={nodes.Human_Brain.geometry} material={materials.material_0} position={[4.14, 0.99, -19.23]} rotation={[0, -1.53, 0]} scale={0.01} />
        <mesh name="Curve001" geometry={nodes.Curve001.geometry} material={materials['SVGMat.005']} position={[-4.53, 0.39, -18.88]} rotation={[Math.PI / 2, 0, -1.58]} scale={15.73} />
        <mesh name="Curve002" geometry={nodes.Curve002.geometry} material={materials['SVGMat.001']} position={[-4.74, 0.39, -23.24]} rotation={[Math.PI / 2, 0, -1.61]} scale={15.73} />
      </group>
    </group>
  )
}

useGLTF.preload('/DPM-legs.gltf')
